#!/bin/bash
set -e
BRANCH=$(git status | grep On | awk '{print $3}')
echo current branch is  $BRANCH
DEP=$1
if [ -z "$DEP" ]; then

	echo "wrong argument"
	exit 1

elif [[ $DEP = $BRANCH  &&  "$DEP" = +(dev|master) ]]; then  
#	git checkout $DEP >/dev/null
	git fetch    >/dev/null
	git diff --stat $DEP origin/$DEP
	git log --since="2 days ago" --pretty=format:"%H","%s","%an" >changelog.txt

elif [[ "${DEP}" != +(dev|master)  ]]; then
	echo not a valid branch
	exit 1
else
	echo "undefined for this branch"
fi
