#!/bin/bash
set -e
BRANCH=$(git status | grep On | awk '{print $3}')
echo current branch is  $BRANCH
DEP=$1
if [ -z "$DEP" ]; then

	echo "wrong argument"
	exit 1

elif [[ $DEP = $BRANCH ]]; then 
	echo "chala" 
#	git checkout $DEP >/dev/null
	git fetch    >/dev/null
	git diff $DEP origin/$DEP
	git log --since="2 days ago" --pretty=format:"%H","%s","%an" >changelog.txt

else
	echo Branches are different
fi
